//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public System.Guid Id { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
