//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid Id { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.Guid ScheduleId { get; set; }
        public System.Guid TransactionTypeId { get; set; }
        public System.Guid ClientId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
